spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            #url: jdbc:mysql://localhost:3306/allen?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
            url: jdbc:mysql://192.168.33.164:3306/test1?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
            username: root
            password: 123456
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

allen:
    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
    shiro:
        redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】

    nodeEndpoint: 192.168.33.164:8545

    fromAddress: "0x1e07567302633f579023fba7b952442dfec89259"

    integralContrctAddress: "0x868a658291b69dde4531fbf598b2d15080da2520"

    integralRecycleAddress: "0x3d8219f37278287b65752876cef17d142993f20f"

    gaslimit: 3000000

    txdata: jieyue
