[parity]
chain = "allen-spec.json"
base_path = "/home/ubuntu/bc/parity0"
[network]
port = 30300
[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
interface = "0.0.0.0"
[ui]
port = 8180
interface = "0.0.0.0"
[websockets]
port = 8450
interface = "0.0.0.0"
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x74b361f65421842682eec056b2b1c0c3c18f1794"
reseal_on_txs = "none"